use clap::{Parser, Subcommand};
use serde::{Deserialize, Serialize};
use std::path::PathBuf;

const ONRAMP_URL: &str = "https://gateway.datagrout.ai/onramp";
const GITIGNORE_ENTRY: &str = "TetherConfig.lua\n";

#[derive(Parser)]
#[command(name = "tether", about = "DataGrout Tether CLI -- bootstrap DG in your Rojo project")]
struct Cli {
    #[command(subcommand)]
    command: Command,
}

#[derive(Subcommand)]
enum Command {
    /// Bootstrap a Tether identity and write TetherConfig.lua
    Init {
        /// Agent name shown in the DataGrout dashboard
        #[arg(long, default_value = "roblox-game")]
        name: String,

        /// Directory to write TetherConfig.lua (defaults to current directory)
        #[arg(long)]
        output: Option<PathBuf>,
    },
    /// Print current credentials from TetherConfig.lua
    Status {
        #[arg(long)]
        config: Option<PathBuf>,
    },
}

#[derive(Debug, Deserialize)]
struct OnrampStep1Response {
    session_token: String,
}

#[derive(Debug, Deserialize)]
struct OnrampStep2Response {
    client_id: String,
    client_secret: String,
    token_url: String,
    mcp_url: String,
    rpc_url: String,
}


fn main() {
    let cli = Cli::parse();

    match cli.command {
        Command::Init { name, output } => cmd_init(name, output),
        Command::Status { config } => cmd_status(config),
    }
}

fn cmd_init(agent_name: String, output: Option<PathBuf>) {
    let out_dir = output.unwrap_or_else(|| std::env::current_dir().expect("cwd"));

    // Check for existing config
    let config_path = out_dir.join("TetherConfig.lua");
    if config_path.exists() {
        println!("TetherConfig.lua already exists -- credentials preserved.");
        println!("Delete it and re-run `tether init` to create a new identity.");
        return;
    }

    println!("Registering with DataGrout (free tier)…");

    let client = reqwest::blocking::Client::new();

    // Step 1: initiate registration
    let resp1 = client
        .post(ONRAMP_URL)
        .json(&serde_json::json!({
            "agent_name": agent_name,
            "agent_type": "roblox-game",
            "intended_use": "game-logic",
        }))
        .send()
        .expect("HTTP request to onramp endpoint failed");

    if !resp1.status().is_success() {
        eprintln!("Registration failed: HTTP {}", resp1.status());
        eprintln!("{}", resp1.text().unwrap_or_default());
        std::process::exit(1);
    }

    let step1: OnrampStep1Response = resp1.json().expect("invalid onramp step 1 response");

    // Step 2: complete registration with session token
    let resp2 = client
        .post(format!("{}/complete", ONRAMP_URL))
        .bearer_auth(&step1.session_token)
        .json(&serde_json::json!({}))
        .send()
        .expect("HTTP request to onramp/complete endpoint failed");

    if !resp2.status().is_success() {
        eprintln!("Registration failed at step 2: HTTP {}", resp2.status());
        eprintln!("{}", resp2.text().unwrap_or_default());
        std::process::exit(1);
    }

    let data: OnrampStep2Response = resp2.json().expect("invalid onramp step 2 response");

    // Write TetherConfig.lua
    let lua = generate_lua_config(
        &data.client_id, &data.client_secret, &data.token_url, &data.mcp_url, &data.rpc_url,
    );

    std::fs::write(&config_path, lua).expect("failed to write TetherConfig.lua");

    // Append to .gitignore if it exists and doesn't already have the entry
    let gitignore = out_dir.join(".gitignore");
    if gitignore.exists() {
        let contents = std::fs::read_to_string(&gitignore).unwrap_or_default();
        if !contents.contains("TetherConfig.lua") {
            let mut appended = contents;
            if !appended.ends_with('\n') {
                appended.push('\n');
            }
            appended.push_str(GITIGNORE_ENTRY);
            std::fs::write(&gitignore, appended).ok();
            println!("Added TetherConfig.lua to .gitignore");
        }
    } else {
        std::fs::write(&gitignore, GITIGNORE_ENTRY).ok();
        println!("Created .gitignore with TetherConfig.lua");
    }

    println!();
    println!("✓ Registered: {}", data.client_id);
    println!("✓ Written:    {}", config_path.display());
    println!();
    println!("Next steps:");
    println!("  1. Add TetherConfig.lua to your Rojo project.json alongside Tether");
    println!("  2. require(Tether).connect() -- credentials load automatically");
    println!("  3. Upgrade at https://app.datagrout.ai/pricing for more credits");
}

fn generate_lua_config(
    client_id: &str,
    client_secret: &str,
    token_url: &str,
    mcp_url: &str,
    rpc_url: &str,
) -> String {
    format!(
        "-- TetherConfig.lua -- generated by `tether init`\n\
         -- DO NOT commit this file. Add TetherConfig.lua to .gitignore.\n\
         \n\
         return {{\n\
         \tclient_id     = \"{}\",\n\
         \tclient_secret = \"{}\",\n\
         \ttoken_url     = \"{}\",\n\
         \tmcp_url       = \"{}\",\n\
         \trpc_url       = \"{}\",\n\
         }}\n",
        client_id, client_secret, token_url, mcp_url, rpc_url,
    )
}

fn cmd_status(config: Option<PathBuf>) {
    let config_path = config.unwrap_or_else(|| {
        std::env::current_dir()
            .expect("cwd")
            .join("TetherConfig.lua")
    });

    if !config_path.exists() {
        println!("No TetherConfig.lua found. Run `tether init` to bootstrap.");
        return;
    }

    println!("Config: {}", config_path.display());

    // Parse just the client_id line for display (avoid a Lua parser dependency)
    let contents = std::fs::read_to_string(&config_path).unwrap_or_default();
    for line in contents.lines() {
        let line = line.trim();
        if line.starts_with("client_id") || line.starts_with("mcp_url") || line.starts_with("rpc_url") {
            println!("  {}", line.trim_end_matches(','));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_lua_config_contains_all_fields() {
        let lua = generate_lua_config(
            "agt_test123",
            "secret_abc",
            "https://gateway.datagrout.ai/servers/uuid/oauth/token",
            "https://gateway.datagrout.ai/servers/uuid/mcp",
            "https://gateway.datagrout.ai/servers/uuid/rpc",
        );
        assert!(lua.contains("client_id"), "missing client_id");
        assert!(lua.contains("agt_test123"), "missing client_id value");
        assert!(lua.contains("client_secret"), "missing client_secret");
        assert!(lua.contains("secret_abc"), "missing client_secret value");
        assert!(lua.contains("token_url"), "missing token_url");
        assert!(lua.contains("mcp_url"), "missing mcp_url");
        assert!(lua.contains("rpc_url"), "missing rpc_url");
        assert!(lua.contains("servers/uuid/rpc"), "missing rpc_url value");
    }

    #[test]
    fn generate_lua_config_is_valid_lua_table() {
        let lua = generate_lua_config("id", "secret", "https://t", "https://m", "https://r");
        assert!(lua.contains("return {"), "missing table open");
        assert!(lua.trim_end().ends_with('}'), "missing table close");
    }

    #[test]
    fn generate_lua_config_has_gitignore_comment() {
        let lua = generate_lua_config("id", "secret", "https://t", "https://m", "https://r");
        assert!(lua.contains("DO NOT commit"), "missing gitignore warning");
    }

    #[test]
    fn cmd_status_matches_expected_fields() {
        // Simulate the line-matching logic used by cmd_status
        let config = "return {\n\
            \tclient_id     = \"agt_abc\",\n\
            \tclient_secret = \"secret\",\n\
            \ttoken_url     = \"https://t\",\n\
            \tmcp_url       = \"https://m\",\n\
            \trpc_url       = \"https://r\",\n\
            }\n";

        let displayed: Vec<&str> = config
            .lines()
            .map(|l| l.trim())
            .filter(|l| {
                l.starts_with("client_id") || l.starts_with("mcp_url") || l.starts_with("rpc_url")
            })
            .collect();

        assert_eq!(displayed.len(), 3);
        assert!(displayed.iter().any(|l| l.contains("agt_abc")));
        assert!(displayed.iter().any(|l| l.contains("mcp_url")));
        assert!(displayed.iter().any(|l| l.contains("rpc_url")));
    }
}
