[package]
name = "tether-cli"
version = "0.2.0"
edition = "2021"
description = "CLI for bootstrapping Tether in Rojo/Wally projects"
license = "MIT"
repository = "https://github.com/datagrout/tether"
homepage = "https://github.com/datagrout/tether"
readme = "../README.md"
keywords = ["roblox", "luau", "datagrout", "wally", "rojo"]
categories = ["command-line-utilities", "game-development"]

[[bin]]
name = "tether"
path = "src/main.rs"

[dependencies]
reqwest = { version = "0.12", features = ["json", "blocking"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
clap = { version = "4", features = ["derive"] }
