-- TetherConfig.lua -- generated by `tether-cli init`
-- DO NOT commit this file. Add it to .gitignore.
--
-- Place this ModuleScript alongside Tether in ReplicatedStorage.
-- Tether loads it automatically; no code changes needed.

return {
  client_id     = "agt_REPLACE",
  client_secret = "REPLACE",
  token_url     = "https://gateway.datagrout.ai/servers/REPLACE/oauth/token",
  mcp_url       = "https://gateway.datagrout.ai/servers/REPLACE/mcp",
  rpc_url       = "https://gateway.datagrout.ai/servers/REPLACE/rpc",
}
