-- TetherConfig.lua -- generated by `tether-cli init`
-- DO NOT commit this file. Add it to .gitignore.
--
-- Place this ModuleScript alongside Tether in SERVERSTORAGE. Never put it in
-- ReplicatedStorage: that container replicates to every player's client, and
-- this file holds your client_secret. Tether loads it automatically from its
-- sibling; no code changes needed.

return {
  client_id     = "agt_REPLACE",
  client_secret = "REPLACE",
  token_url     = "https://gateway.datagrout.ai/servers/REPLACE/oauth/token",
  mcp_url       = "https://gateway.datagrout.ai/servers/REPLACE/mcp",
  rpc_url       = "https://gateway.datagrout.ai/servers/REPLACE/rpc",
}
